const { getMemberListController, createMemberController, getMemberController, editMemberController,
  deleteMemberController, removeMemberController, addMemberController } = require('../controllers/membercontrollers');
const { getSurveyListController, createSurveyController, getRecentResponseController, getSurveyController,
  sendResponseController, deleteSurveyController, getResponsesController } = require('../controllers/surveycontrollers');
const { getProjectListController, createProjectController, deleteProjectController } = require('../controllers/projectcontrollers');
const { editSettingsController } = require('../controllers/settingcontrollers');
const {getAllAccountInfoController,
  getRequestsController,
  getInfoBriefController,
  getAllInfoController,
  getAccountInfoController,
  getAdminsController,
  createAccountController,
  addAdminController,
  decideRequestController,
  editAccountController,
  deleteAccountController,
  deleteAdminController,} = require('../controllers/admincontrollers')


module.exports = {
  getMemberListController,
  createMemberController,
  getSurveyListController,
  createSurveyController,
  getProjectListController,
  createProjectController,
  editSettingsController,
  getMemberController,
  getRecentResponseController,
  getSurveyController,
  createProjectController,
  sendResponseController,
  editMemberController,
  deleteMemberController,
  deleteProjectController,
  deleteSurveyController,
  getResponsesController,
  removeMemberController,
  addMemberController,
  getAllAccountInfoController,
  getRequestsController,
  getInfoBriefController,
  getAllInfoController,
  getAccountInfoController,
  getAdminsController,
  createAccountController,
  addAdminController,
  decideRequestController,
  editAccountController,
  deleteAccountController,
  deleteAdminController,
}