module.exports = {
  ROLES:{
    ADMIN: "ADMIN",
    MEMBER: "MEMBER",
    SUPER_ADMIN: "SUPER_ADMIN",
    OWNER: "OWNER"
  },
  PACKAGES:{
    FREE_TRAIL: "FREE TRAIL",
    UNLIMITED: "UNLIMITED"
  },
  CHECK:{
    MEMBER: "MEMBER",
    SURVEY: "SURVEY",
    PROJECT: "PROJECT"
  },
  PLATFORMS:[
    "SEBSIB_OFFICE_1",
    "SEBSIB_COLLECT_2"
  ]
}